---
title: "Elaboração dos anexos anexos/tabelas"
editor: visual
lang: "pt"
format:
  # docx: default
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
---

```{r}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(plotly)
library(knitr)
library(kableExtra)
library(DescTools)
library(zoo)
library(stringr)
library(DT)
library(stringr)
library(scales)
library(ggthemes)

options(DT.options = list(pageLength = 10, fontSize = "70%", language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json')))
```

```{r}
# 
# dados_despesa <- read_excel("auto_despesa.xlsx") %>% clean_names()
# 
# 
# dados_receita <- read_excel("auto_receita.xlsx") %>% clean_names()
# 
# 
# dados_conta_contabil <- read_excel("auto_conta_contabil.xlsx") %>% clean_names()
# 
# 
# dados_restos_a_pagar <- read_excel("auto_restos_a_pagar.xlsx") %>% clean_names()
```

```{r}
# library(openxlsx)
# 
# # https://www.youtube.com/watch?v=SDV2jB731Fo
# 
# wb <- createWorkbook()
# 
# addWorksheet(wb, "receitas")
# addWorksheet(wb, "despesas")
# addWorksheet(wb, "conta_contabil")
# addWorksheet(wb, "restos_a_pagar")
# 
# writeData(wb, "receitas",df_receita %>% group_by(chave) %>% summarise(previsao_atualizada_da_receita = sum(previsao_atualizada_da_receita, na.rm = TRUE)/1000000, receita_orcamentaria_liquida = sum(receita_orcamentaria_liquida, na.rm = TRUE)/1000000) )
# 
# writeData(wb, "despesas",df_despesa %>% group_by(chave) %>% summarise(dotacao_atualizada = sum(dotacao_atualizada, na.rm = TRUE)/1000000, despesas_empenhadas_controle_empenho = sum(despesas_empenhadas_controle_empenho, na.rm = TRUE)/1000000, despesas_liquidadas_controle_empenho = sum(despesas_liquidadas_controle_empenho, na.rm = TRUE)/1000000, despesas_pagas_controle_empenho = sum(despesas_pagas_controle_empenho, na.rm = TRUE)/1000000) )
# 
# saveWorkbook(wb, file = "dados_salvos.xlsx", overwrite = TRUE)
```
