---
title: "monitor"
---

```{r bibliotecas}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(plotly)
library(knitr)
library(kableExtra)
library(DescTools)
library(zoo)
library(stringr)
library(DT)
library(stringr)
library(scales)
library(ggthemes)

`%notin%` <- Negate(`%in%`)
myNumFmt <- as.fmt(digits=0, big.mark=".")
options(scipen = 999)

options(DT.options = list(pageLength = 10, fontSize = "70%", language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese.json')))
# https://rstudio.github.io/DT/004-i18n.html
# https://rstudio.github.io/DT/options.html
# %>% formatCurrency(c('A', 'C')) %>% formatPercentage('D', 2)%>% formatRound('E', 3)
```

```{r}
monitor_fontes <- read_excel("C:/Users/andre.ferrari/OneDrive - Secretaria do Tesouro Nacional/General/3. Projetos/2. Execução/automate/regra_de_ouro/monitor_fontes.xlsx") %>% clean_names()
```

```{r}
calendario <- read.csv("calendario.csv") %>% select(dia)



dia <-  format(parse_date_time((as.data.frame(str_split( tail(monitor_fontes,1)[1],"\n"))[3,1]),"%d/%m/%Y"),"%Y_%m_%d")



calendario = rbind(calendario, dia) %>% unique() %>% arrange(dia)



write.csv(calendario, "calendario.csv", row.names = FALSE)

```

```{r}
write.csv(monitor_fontes, str_c(dia,".csv"), row.names = FALSE)
```

```{r}
atual <- str_c(tail(calendario,1)[1,1],".csv") 
anterior <- str_c(tail(calendario,2)[1,1],".csv")

base_atual <- head(read_csv(atual, 
                        locale = locale(decimal_mark = ",", grouping_mark = ".", 
                                        encoding = "latin1")) ,-1)




base_anterior <- head(read_csv(anterior, locale = locale(decimal_mark = ",", grouping_mark = ".", 
                                        encoding = "latin1")),-1)




setdiff(base_anterior ,base_atual) 

names(base_atual)[3]="saldo_atual"
names(base_anterior)[3]="saldo_anterior"

comparacao <- full_join(base_anterior, base_atual, by = c("fonte_recursos_nome" , "fonte_recursos_codigo") ) %>% 
    mutate_at(c('saldo_atual','saldo_anterior'), ~replace_na(.,0))

comparacao <-  comparacao %>% mutate(diferenca_real = saldo_atual-saldo_anterior, diferenca_percentual = diferenca_real/saldo_anterior*100) %>% filter(saldo_anterior== 0)%>% mutate(dia= dia) 

datatable(comparacao)


log_comparacao <- read.csv("~/R/automate/log_comparacao.csv")  
  
log_comparacao <-   rbind(log_comparacao,comparacao ) %>% unique()



write.csv(log_comparacao, "log_comparacao.csv", row.names = FALSE)

datatable(log_comparacao %>% select(fonte_recursos_codigo, fonte_recursos_nome, saldo_anterior, dia))
```

```{r}

# arquivos_tg <- list.files("C:/Users/andre.ferrari/OneDrive - Secretaria do Tesouro Nacional/General/3. Projetos/2. Execução/automate/regra_de_ouro","monitor")
# 
# funcao_ler_arquivos <- function(x){ read_excel(x) %>% clean_names() %>% mutate(dia =  format(parse_date_time((as.data.frame(str_split( tail(monitor_fontes,1)[1],"\n"))[3,1]),"%d/%m/%Y"),"%Y_%m_%d"))}
# 
# arquivos_lidos <- map_df( str_c ("C:/Users/andre.ferrari/OneDrive - Secretaria do Tesouro Nacional/General/3. Projetos/2. Execução/automate/regra_de_ouro/", arquivos_tg), funcao_ler_arquivos) 
# 
# 
# links <- map( str_c ("C:/Users/andre.ferrari/OneDrive - Secretaria do Tesouro Nacional/General/3. Projetos/2. Execução/automate/regra_de_ouro/", arquivos_tg), str_c()) 
# 
# 
# 
# funcao_ler_arquivos_dia <- function(x){ read_excel(x) %>% clean_names() %>% mutate(dia =  format(parse_date_time((as.data.frame(str_split( tail(x,1)[1],"\n"))[3,1]),"%d/%m/%Y"),"%Y_%m_%d"))}
# 
# arquivos_lidos_dia <- map_df( str_c ("C:/Users/andre.ferrari/OneDrive - Secretaria do Tesouro Nacional/General/3. Projetos/2. Execução/automate/regra_de_ouro/", arquivos_tg),funcao_ler_arquivos_dia) 


```
